## Transform NON SQUARE to SQUARE MATRIX

In [51]:
import numpy as np

nonsquare = np.random.random(size=(3, 5))

l, c = nonsquare.shape
print('rows:',l ,'  Columns:',c)
width = max(l, c)
square = np.zeros((width, width))
square[:l, :c] = nonsquare

rows: 3   Columns: 5


In [52]:
min_rows = np.min(nonsquare, axis=1)
print(min_rows, width)

[0.02178452 0.08821754 0.02249603] 5


In [53]:
min_cols = np.min(nonsquare, axis=0)
print(min_rows, width)

[0.02178452 0.08821754 0.02249603] 5


In [54]:
nonsquare

array([[0.02178452, 0.35785148, 0.23184412, 0.63562851, 0.02386369],
       [0.08821754, 0.94100779, 0.34836852, 0.57795861, 0.29520108],
       [0.02249603, 0.34157811, 0.41260547, 0.91899155, 0.79113968]])

In [55]:
square

array([[0.02178452, 0.35785148, 0.23184412, 0.63562851, 0.02386369],
       [0.08821754, 0.94100779, 0.34836852, 0.57795861, 0.29520108],
       [0.02249603, 0.34157811, 0.41260547, 0.91899155, 0.79113968],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])